### ISSUE TITLE
Single line comments join a asterisk(*) every time cleaning

### ISSUE THREAD

**Issue by xekri** [SeanJM/css-clean#26]
Comments like below join a "* " after "/*" clean every time.
`/* some comments in css file */`
after clean:
`/* * some comments in css file */`
I think it's a new bug.
And, still, css-clean will remove all the properties after some properties doesn't know. Hope it can be configured to disable this "feature".

**Comment by xekri** [comment]
All right, I update now and find it solved

**Comment by SeanJM** [comment]
i just posted a patch. If you'd like, check if it still throws a bug. If it does, I can fix it if you paste the exact comment.

Please try to be civil.

Not all properties are supported. Because of how I parse the CSS I have to specify exact properties, this parsing is what does the sorting.

If you run across properties which are ignored, post them as a bug report. Or even better, you can commit a patch yourself and issue a pull request.

**Comment by xekri** [comment]
Sorry, I'm not native English speaker and maybe seemed rude to you, I didn't mean it.
I now know how it works and I can still use a separate file to contain some hacks for IE6,7,8...
That's a very special situation, I don't expect you to fix them cause those properties are very outdated.

**Comment by SeanJM** [comment]
Okay. Adding missing properties is easy, the file is just a list.
